using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace momentum
{
    /// <summary>
    /// Interaction logic for iphone_11_pro_max___5.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class iphone_11_pro_max___5 : ContentPage
    {
        public iphone_11_pro_max___5()
        {
            InitializeComponent();
        }
    }
}
	