using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace momentum
{
    /// <summary>
    /// Interaction logic for momentum.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class momentum : ContentPage
    {
        public momentum()
        {
            InitializeComponent();
        }
    }
}
	